---
driver:
  name: vz
  network:
    Bridged:
      dhcp: true
  customize:
    cpus: 1
    memory: 1G
    disk: 10G

provisioner:
  name: chef_zero
  cookbooks_path: test/fixtures/cookbooks
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: el6
    driver:
      ostemplate: centos-minimal-6-x86_64

suites:
  - name: standalone
    run_list:
      - recipe[mongotest::test_standalone]

  - name: replset1
    run_list:
      - recipe[mongotest::test_replset]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.10/24

  - name: replset2
    run_list:
      - recipe[mongotest::test_replset]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.11/24

  - name: replset3
    run_list:
      - recipe[mongotest::test_replset_init]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.12/24
