---
driver:
  name: vz
  network:
    Bridged:
      dhcp: true
  customize:
    cpus: 1
    memory: 512M
    disk: 5G

provisioner:
  name: chef_zero
  cookbooks_path: test/fixtures/cookbooks
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: el6
    driver:
      ostemplate: centos-minimal-6-x86_64

suites:
  - name: replset1
    run_list:
      - recipe[mongotest::test_replset]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.10/24

  - name: replset2
    run_list:
      - recipe[mongotest::test_replset]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.11/24

  - name: replset3
    run_list:
      - recipe[mongotest::test_replset_init]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.12/24

  - name: shard1
    run_list:
      - recipe[mongotest::test_shard]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.13/24

  - name: shard2
    run_list:
      - recipe[mongotest::test_shard]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.14/24

  - name: cfg1
    run_list:
      - recipe[mongotest::test_cfg]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.15/24

  - name: cfg2
    run_list:
      - recipe[mongotest::test_cfg]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.16/24

  - name: cfg3
    run_list:
      - recipe[mongotest::test_cfg_init]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.17/24

  - name: shard_set1
    run_list:
      - recipe[mongotest::test_shard_set]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.21/24

  - name: shard_set2
    run_list:
      - recipe[mongotest::test_shard_set]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.22/24

  - name: shard_set3
    run_list:
      - recipe[mongotest::test_shard_init]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.23/24

  - name: mongos_ci
    run_list:
      - recipe[mongotest::test_mongos_ci]
    driver:
      network:
        Private_Network:
          ip: 172.16.20.18/24
